### ISSUE TITLE
SortMeRNA differentially filters R1 & R2, leading to unpaired read files 

### ISSUE THREAD

**Issue by RodolfoSalido** [qiita-spots/qp-meta#11]
Read counts after SortMeRNA for "...nonribosomal.R1.fastq.gz" differ from "...nonribosomal.R2.fastq.gz", leading to issues with unpaired reads for downstream analyses.

**Comment by antgonza** [comment]
This is correct. Note that the downstream steps in Qiita work fine with unpaired reads. What's the tool you are having issues with?

**Comment by RodolfoSalido** [comment]
Funny enough, it's bowtie2, packaged with the [CARD Resistance Gene Identifier (RGI) software. ](https://github.com/arpcard/rgi)

**Comment by antgonza** [comment]
I guess they are using a different set of parameters in bowtie2, could you confirm this? Maybe this is a good discussion for FutureTech.

**Comment by RodolfoSalido** [comment]
Daniel is under the assumption that read files get concatenated and piped to the bowtie2 command for woltka, can you confirm? I'll look for the bowtie2 command the rgi uses.

**Comment by antgonza** [comment]
That's correct; for woltka the r1 and r2 are treated as r1 by concatenating r2 at the end of r1.

**Comment by RodolfoSalido** [comment]
I see. rgi bowtie2 defaults to a function that assumes paired end reads when an r2 file is specified. I'll just concatenate r1&r2 to circumvent this issue for now. 
```

	def align_bowtie2(self, reference_genome, index_directory, output_sam_file):
		"""
		Align paired reads to reference database selected (i.e card, wildcard etc) using bowtie2
		"""
		self.check_index(index_directory=index_directory, reference_genome=reference_genome)

		logger.info("align reads -1 {} -2 {} to {}".format(self.read_one, self.read_two, reference_genome))

		cmd = "bowtie2 --quiet --very-sensitive-local --threads {threads} -x {index_directory} -1 {read_one} -2 {read_two}  -S {output_sam_file}".format(
			threads=self.threads,
			index_directory=index_directory,
			read_one=self.read_one,
			read_two=self.read_two,
			output_sam_file=output_sam_file
		)

		os.system(cmd)

```

I'm not sure if this unpaired reads issue with surface again
